# Workflow for automated Emacs builds

name: build

permissions:
  contents: write

# Controls when the action will run.
on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at 00:00 UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      emacs_repo:
        description: 'Emacs Git Repository'
        required: false
        default: 'https://github.com/emacs-mirror/emacs.git'
      emacs_branch:
        description: 'Emacs Branch'
        required: false
        default: 'emacs-31'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare_env:
    name: Prepare build version
    runs-on: ubuntu-latest
    env:
      EMACS_REPO: ${{ github.event.inputs.emacs_repo || 'https://github.com/emacs-mirror/emacs.git' }}
      EMACS_BRANCH: ${{ github.event.inputs.emacs_branch || 'emacs-31' }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Get build version
        id: vars
        run: |
          mkdir -p ./git/emacs
          cd ./git/emacs/
          git clone --depth 1 --branch ${{ env.EMACS_BRANCH }} ${{ env.EMACS_REPO }} .
          ts=`date +'%Y%m%d'`
          commit=`git rev-parse --short=8 HEAD`
          major_ver=`cat configure.ac | grep -Po 'AC_INIT\(.*\[\K\d+'`
          version=`echo ${major_ver}.${{ github.run_number }}.${ts}.${commit}`

          echo "commit=${commit}" >> $GITHUB_ENV
          echo "version=${version}" >> $GITHUB_ENV
          echo "pkg_version=${major_ver}.${{ github.run_number }}.0.0" >> $GITHUB_ENV
    outputs:
      repo: ${{ env.EMACS_REPO }}
      branch: ${{ env.EMACS_BRANCH }}
      version: ${{ env.version }}
      pkg_version: ${{ env.pkg_version }}
      commit: ${{ env.commit }}

  build_windows:
    needs: prepare_env
    name: Build Emacs
    # Matrix strategy from
    # https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025
            shell: powershell
            msystem: MINGW64
            emacs_options: --without-mps
            extension_options: --pdf-tools --hunspell --mu --isync --cmigemo
          - os: windows-2025
            shell: powershell
            msystem: UCRT64
            emacs_options: --variant mps --with-mps --no-strip --enable-build-details
            extension_options: --pdf-tools --hunspell --mu --isync --cmigemo
          - os: windows-11-arm
            shell: powershell
            msystem: CLANGARM64
            emacs_options: --without-native-compilation --without-mps
            extension_options: --pdf-tools --hunspell --cmigemo

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    env:
      EMACS_REPO: ${{ needs.prepare_env.outputs.repo }}
      EMACS_BRANCH: ${{ needs.prepare_env.outputs.branch }}
      EMACS_COMMIT: ${{ needs.prepare_env.outputs.commit }}
      EMACS_PKG_VERSION: ${{ needs.prepare_env.outputs.pkg_version }}
      EMACS_CERT_SECRET: ${{ secrets.EMACS_CERT_SECRET }}
      MSYSTEM: ${{ matrix.msystem }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ./git
            ./build
            ./zips
          key: emacs-build-cache-${{ runner.os }}-${{ matrix.msystem }}-${{ needs.prepare_env.outputs.commit }}
          restore-keys: |
            emacs-build-cache-${{ runner.os }}-${{ matrix.msystem }}-

      - name: Setup Msys2
        id: msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          release: ${{ matrix.os == 'windows-11-arm' && 'true' || 'false' }}

      - name: Update MSYS2_DIR environment variable
        run: |
          echo "MSYS2_DIR=${{ steps.msys2.outputs.msys2-location }}" >> $env:GITHUB_ENV

      # This is the shortest job, but in this case it pulls all MSYS/MINGW64
      - name: Clone Emacs
        run: .\emacs-build.cmd --clone --repo $env:EMACS_REPO --branch $env:EMACS_COMMIT

      - name: Install deps
        run: |
          .\emacs-build.cmd --slim --branch $env:EMACS_COMMIT --ensure ${{ matrix.emacs_options }}

      - name: Build Emacs
        # Require --with-* flags, else the deps will not be included properly
        run: |
          .\emacs-build.cmd --slim --branch $env:EMACS_COMMIT --configure --build-dev ${{ matrix.emacs_options }}

      - name: Package Emacs
        run: |
          $env:MSIXHeroCLI = &where.exe MSIXHeroCLI
          if ($env:MSIXHeroCLI) {
            .\emacs-build.cmd --slim --branch $env:EMACS_COMMIT --msix --pack-all ${{ matrix.emacs_options }} ${{ matrix.extension_options }}
          } else {
            .\emacs-build.cmd --slim --branch $env:EMACS_COMMIT --pack-all ${{ matrix.emacs_options }} ${{ matrix.extension_options }}
          }

      # Upload release for each build
      - name: Upload binaries to release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ./zips/*{_full.zip,.msix}
          file_glob: true
          tag: v${{ needs.prepare_env.outputs.version }}
          release_name: emacs_${{ needs.prepare_env.outputs.version }}
          draft: false
          prerelease: false
